const DEFAULT_KEYWORDS = [
  'token alert',
  'quick buy',
  'quick entry!',
  'gmgn.ai',
  '24h change',
  'wallet',
  'signal',
  'gempump',
  't.me/',
  '💎',
  'called in my',
  'memefast',
  'spot early',
  'giving away',
  'giveaway',
  'private tg',
  'first alert',
  'tg frens',
  'token:',
  'my telegram',
  '💎 discover',
  'holds:',
  '🚨🚨',
  '💰',
  'ant.fun',
  'earn points',
  'early entry',
  'tg',
  'my call',
  '💸',
  '🚀',
  'gmgn',
  'sniperbot',
  'free calls',
  'our bot',
  'solana smart wallets',
  'ai alpha',
  'spot trends before',
  'ai alert',
  'ai summary',
  'check analyze',
  'fast trading',
  'trading insights',
  'smart wallets bought',
  'smart wallets sold',
  'signal powered by',
  'users analytics',
  ' hype score', 
  'follow me', 
  'alpha group',
  'join the tg', 
  'entered trending', 
  'vip tg', 
  'trading platform', 
  '24h volume', 
  'overall score', 
  'vip alert'
];

const DEFAULT_THRESHOLD = 2;

// only run on “search” pages with addr/ticker
const DEFAULT_FILTER_SEARCH_ONLY = false;
const DEFAULT_FILTER_AUTOMATED = false;
